config/routes.rb
CmsByToni::Application.routes.draw do

	devise_for :users, controllers: { registrations: "registrations", sessions: "sessions"  }
	get "texts/show", path: :clanki
	root "news#index" 
	resources :news, only: [ :index, :show ], path: :kategorija
	resources :categories, :subcategories, :articles

end

app/models/article.rb
class Article < ActiveRecord::Base
	belongs_to :subcategory

	validates :name, length: { minimum: 5, maximum: 50 }
	validates :body, length: { minimum: 50,  maximum: 2000 }
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :subcategories

	validates :name, length: { minimum: 5, maximum: 20 }
end

app/models/subcategory.rb
class Subcategory < ActiveRecord::Base
	belongs_to :category
	has_many :articles

	validates :name, length: { minimum: 5, maximum: 20 }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	before_action :authenticate_user!
	add_breadcrumb "Domov", :categories_path

  def index
	  @subcategory = Subcategory.find(params[:id])
	  @articles = @subcategory.articles.all
	  @category = Category.find(@subcategory.category_id) #to je za breadchrumps
	  add_breadcrumb @category.name, controller: 'subcategories', action: 'index', id: @category.id
	  add_breadcrumb @subcategory.name, action: 'index', id: @subcategory.id
  end

  def new
	  @subcategory = Subcategory.find(params[:id])
	  @article = @subcategory.articles.build
	  @category = Category.find(@subcategory.category_id) #to je za breadchrumps
	  add_breadcrumb @category.name, controller: 'subcategories', action: 'index', id: @category.id
	  add_breadcrumb @subcategory.name, action: 'index', id: @subcategory.id
  end

  def create
	  @subcategory = Subcategory.find(params[:id])
	  @article = @subcategory.articles.build(article_params)
	  @category = Category.find(@subcategory.category_id) #to je za breadchrumps
	  add_breadcrumb @category.name, controller: 'categories', action: 'index', id: @category.id
	  add_breadcrumb @subcategory.name, action: 'index', id: @subcategory.id

	  if @article.save
		  redirect_to action: :index, id: @article.subcategory_id
			flash[:notice] = "Uspešno ste dodali nov članek z naslovom #{@article.name}" 
		  else
			  render :new
		  end

  end


  def edit
	  @article = Article.find(params[:id])
	  @subcategory = Subcategory.find(@article.subcategory_id)
	  @category = Category.find(@subcategory.category_id) #to je za breadchrumps
	  add_breadcrumb @category.name, controller: 'subcategories', action: 'index', id: @category.id
	  add_breadcrumb @subcategory.name, action: 'index', id: @subcategory.id
	  add_breadcrumb @article.name, action: 'edit', id: @article.id
  end

  def update
	  @article = Article.find(params[:id])

		if @article.update(article_params)
			redirect_to action: :index, id: @article.subcategory_id 
			flash[:notice] = "Uspešno ste spremenili članek v #{@article.name}" 
			else
				render 'edit'
		end
  end

  def destroy
		@article = Article.find(params[:id])
		@article.destroy
		redirect_to action: :index, id: @article.subcategory_id
			flash[:notice] = "Uspešno ste izbrisali članek z naslovom #{@article.name}" 

  end
	private
	def article_params
		params.require(:article).permit(:name, :body) 

	end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	before_action :authenticate_user!

	add_breadcrumb "Domov", :categories_path

	def index
		@categories = Category.all
	end

	def new
		@category = Category.new
	end

	def create
		@category = Category.new(category_params)

		if @category.save
			redirect_to categories_path
			flash[:notice] = "Uspešno ste ustvarili novo kategorijo #{@category.name}" 
		else
			render 'new'
		end
	end

	def edit
		@category = Category.find(params[:id])
	end

	def update
		@category = Category.find(params[:id])
		if @category.update(category_params)
			redirect_to categories_path
			flash[:notice] = "Uspešno ste spremenili  kategorijo v #{@category.name}" 
			else
				render 'edit'
			end
	end
	 def destroy
		@category = Category.find(params[:id])
		@category.destroy
		redirect_to categories_path
		flash[:notice] = "Uspešno ste izbrisali  kategorijo #{@category.name}" 
	 end

	private
	def category_params
		params.require(:category).permit(:name) 

	end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController

	layout 'news'

	add_breadcrumb "Domov", :root_path

	def index
		@categories = Category.all
	end

	def show

		@categories = Category.all

		@subcategories = Subcategory.find(params[:id])
		@articles = @subcategories.articles

		add_breadcrumb @subcategories.name, news_path

	end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
	private
	    def after_sign_up_path_for(resource)
			    '/categories'
		end
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
	private
	    def after_sign_in_path_for(resource)
			    '/categories'
		end
end

app/controllers/subcategories_controller.rb
class SubcategoriesController < ApplicationController
	def index
		@category = Category.find(params[:id])
		@subcategories = @category.subcategories.all
	end

	def new
		@category = Category.find(params[:id])
		@subcategory = @category.subcategories.build
	end

	def create
		@category = Category.find(params[:id])
		@subcategory = @category.subcategories.build(subcategory_params)

		if @subcategory.save
			redirect_to subcategories_path(id: @category.id)
			flash[:notice] = "Uspešno ste dodali novo podkategorijo z naslovom #{@subcategory.name}"
		else
			render 'new'
		end
	end

	def edit
		@subcategory = Subcategory.find(params[:id])
	end
def update
		@subcategory = Subcategory.find(params[:id])

		if @subcategory.update(subcategory_params)
			redirect_to action: :index, id: @subcategory.category_id
			flash[:notice] = "Uspešno ste spremenili naslov podkategorije v #{@subcategory.name}"
			else
				render 'edit'
			end

	end

	def destroy
		@subcategory = Subcategory.find(params[:id])
		@subcategory.destroy
			flash[:notice] = "Uspešno ste izbrisali podkategorijo #{@subcategory.name}"
			redirect_to action: :index, id: @subcategory.category_id

	end

	private
	def subcategory_params
		params.require(:subcategory).permit(:name) 

	end
end

app/controllers/texts_controller.rb
class TextsController < ApplicationController
	layout 'news'

	add_breadcrumb "Domov", :root_path

	def show
		@categories = Category.all
		@article = Article.find(params[:id])
		@subcategorie = Subcategory.find(@article.subcategory_id)

		add_breadcrumb @subcategorie.name, controller: :news, action: :show, id: @subcategorie.id
		add_breadcrumb @article.name, controller: :texts, action: :show, id: @article.id

	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/subcategories_helper.rb
module SubcategoriesHelper
end

app/helpers/texts_helper.rb
module TextsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_error_messages.html.erb
	<% if @article.errors.any? %>
		<ul>
			<% @article.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
			<% end %>
		</ul>
	<% end %>

app/views/articles/edit.html.erb
<h2 class="text-center">Uredi Članek</h2>
<%= bootstrap_form_for @article do |f| %>

	<%= render 'error_messages' %>

	<div><%= f.text_field :name, label: 'Naslov:', placeholder: 'vnesite naslov članka...', autofocus: true %></div>

	<div><%= f.text_area :body, label: 'Besedilo:', placeholder: 'napišite članek...', rows: 25 %></div>
	<div><%= f.submit 'shrani', class: 'btn btn-primary btn-lg' %></div>
<% end %>
<%= link_to 'nazaj', { action: :index, id: @article.subcategory_id }, class: 'btn btn-default' %>

app/views/articles/index.html.erb
<h2 class="text-center">Vsi članki <%= @subcategory.name %></h2>
<% if @articles.empty? %>
	<p class="text-center">Ni nobenega članka. Bodi Kralj in napiši kakšnega.</p>
<% else %>
	<% @articles.each do |item| %>
		<div>
			 <%= link_to item.name, edit_article_path(item), class: 'btn btn-success btn-lg' %>
			<%= link_to 'izbriši', article_path(item), method: :delete, data: { confirm: "Ali ste prepričani, da želite izbrisati članek?" }, class: 'btn btn-default' %> </div>
	<% end %>
<% end %><br>

<%= link_to 'Napiši nov članek', { action: :new, id: @subcategory.id }, class: 'btn btn-primary btn-lg' %><br>
<%= link_to 'Nazaj', { controller: :subcategories, action: :index, id: @subcategory.category_id }, class: 'btn btn-default' %>

app/views/articles/new.html.erb
<h2 class="text-center">Nov članek</h2>

<%= bootstrap_form_for @article, url: { action: :create, id: @subcategory.id} do |f| %>

	<%= render 'error_messages' %>

	<div><%= f.text_field :name, label: 'Naslov:', placeholder: 'vnesite naslov članka...', autofocus: true %></div>

	<div><%= f.text_area :body, label: 'Besedilo:', placeholder: 'napišite članek...', rows: 25 %></div>
	<div><%= f.submit 'shrani', class: 'btn btn-primary btn-lg' %></div>

	<%= link_to 'nazaj', { action: :index, id: @subcategory.id }, class: 'btn btn-default' %>
<% end %>

app/views/categories/_error_messages.html.erb
	<% if @category.errors.any? %>
		<ul>
			<% @category.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
			<% end %>
		</ul>
	<% end %>

app/views/categories/edit.html.erb
<h2 class="text-center">Spremeni naslov kategorije</h2>
<%= bootstrap_form_for @category do |f| %>

	<%= render 'error_messages' %>

	<div><%= f.text_field :name, label: 'Ime:', autofocus: true %></div>
	<div><%= f.submit 'shrani spremembe', class: 'btn btn-primary btn-lg'  %></div>
<% end %>

<%= link_to 'nazaj', categories_path, class: 'btn btn-default' %>

app/views/categories/index.html.erb
<% @home_page = true #this is just for not displaying breadchrumps at index page %>

<h2 class="text-center">Vse kategorije</h2>

<% @categories.each do |category| %>
	<div>
		<%= link_to category.name, { controller: :subcategories, action: :index, id: category.id }, class: 'btn btn-success btn-lg' %>
		<%= link_to 'uredi', edit_category_path(category), class: 'btn btn-default' %>
		<%= link_to 'Izbriši', category_path(category), method: :delete, data: { confirm: "Ali ste prepričani, da želite izbrisati kategorijo?" }, class: 'btn btn-default' %>
	</div>
<% end %>
<br>
<div><%= link_to 'Dodaj novo kategorijo', new_category_path, class: 'btn btn-primary'%></div>

app/views/categories/new.html.erb
<h2 class="text-center">Vnesi novo kategorijo</h2>
<%= bootstrap_form_for @category do |f| %>

	<%= render 'error_messages' %>

	<div><%= f.text_field :name, label: 'Ime:', placeholder: 'Vnesite ime kategorije...', autofocus: true %></div>
	<div><%= f.submit 'Shrani', class: 'btn btn-primary btn-lg' %></div>
<% end %>

<%= link_to 'nazaj', categories_path, class: 'btn btn-default'  %> 

app/views/news/index.html.erb
<% @home_page = true #this is just for not displaying breadchrumps at index page %>

<br>
<br>
<br>

<div class="row text-center color">
	<h1>Dobrodošli na naši spletni strani</h1>
	<p>Lorem ipsum je napol naključni tekst, ki se ga uporablja kot “polnilni” tekst, predvsem kadar se prikazuje grafično podobo spletne strani, ki še nima vsebine. Seveda ne moremo pokazati popolnoma prazne strani, saj ne bo izgledala tako kot bo izgledala ko bo polna vsebine. Raziskave pa so pokazale tudi, da ni pametno pokazati nekega naključnega teksta, saj bo tekst motil ljudi ko gledajo grafično podobo.</p>
</div>

<br>
<br>
<br>
<br>

<div class="row text-center">
	<div class="col-md-4"> <span class=" a glyphicon glyphicon-user big"></span></div>
	<div class="col-md-4"> <span class=" b glyphicon glyphicon-comment big"></span></div>
	<div class="col-md-4"> <span class=" c glyphicon glyphicon-tree-conifer big"></span></div>
</div>

app/views/news/show.html.erb
<div class="row">
	<div class="col-lg-offset-3 col-lg-6">
		<h1>Vse novice za <%= @subcategories.name %></h1>

		<% if @articles.empty? %>
			<h4>V tej kategoriji ni novic. Se opravičujemo za nevšečnost :)</h4>
		<% end %>

		<% for article in @articles %>
			<div><%= link_to article.name,  controller: :texts, action: :show, id: article.id %>
			- pretekel čas od objave: <%= time_ago_in_words(article.created_at) %>
		</div>
		<% end %>
	</div>
</div>

app/views/subcategories/_error_messages.html.erb
	<% if @subcategory.errors.any? %>
		<ul>
			<% @subcategory.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
			<% end %>
		</ul>
	<% end %>

app/views/subcategories/edit.html.erb
<h2 class="text-center">Spremeni naslov podkategorije</h2>
<%= bootstrap_form_for @subcategory do |f| %>

	<%= render 'error_messages' %>

	<div><%= f.text_field :name, label: 'Ime:',  autofocus: true %></div>
	<div><%= f.submit 'shrani', class: 'btn btn-primary btn-lg' %></div>
<% end %>

<%= link_to 'nazaj', { action: :index, id: @subcategory.category_id }, class: 'btn btn-default' %>

app/views/subcategories/index.html.erb
<h2 class="text-center">Vse podkategorije za <%= @category.name %></h2>
<% if @subcategories.empty? %>
	<p class="text-center">Ni nobene podkategorije. Bodi car in vnesi eno. </p>
<% else %>
	<% @subcategories.each do |item| %>
		<div><%= link_to item.name, { controller: :articles, action: :index, id: item.id }, class: 'btn btn-success btn-lg' %>
			<%= link_to 'uredi', edit_subcategory_path(item), class: 'btn btn-default' %>
			<%= link_to 'izbriši', subcategory_path(item), method: :delete, data: { confirm: "Ali ste prepričani, da želite izbrisati podkategorijo?" }, class: 'btn btn-default' %> </div>
	<% end %>
<% end %><br>
<%= link_to 'Dodaj podkategorijo', { action: :new, id: @category.id }, class: 'btn btn-primary' %><br>
<%= link_to 'Nazaj', categories_path, class: 'btn btn-default' %>

app/views/subcategories/new.html.erb
<h2 class="text-center">Vnesi novo podkategorijo</h2>

<%= bootstrap_form_for @subcategory, url: { action: :create, id: @category.id} do |f| %>

	<%= render 'error_messages' %>

	<div><%= f.text_field :name, label: 'Ime:', placeholder: 'Vnesite ime nove podkategorije...', autofocus: true %></div>
	<div><%= f.submit 'shrani', class: 'btn btn-primary btn-lg' %></div>
<% end %>
<%= link_to 'Nazaj', { action: :index, id: @category.id }, class: 'btn btn-default' %>

app/views/texts/show.html.erb
<div class="row">
	<div class="col-lg-offset-3 col-lg-6">
		<h1><%= @article.name %></h1>
		<p><%= @article.created_at.strftime("%d %b. %Y") %></p>
		<div class="text-justify"><%= simple_format( @article.body ) %></div>
	</div>
</div>