config/routes.rb
CmsByToni::Application.routes.draw do

	devise_for :users, controllers: { registrations: "registrations", sessions: "sessions"  }
	get "texts/show", path: :clanki
	root "news#index" 
	resources :news, only: [ :index, :show ], path: :kategorija
	resources :categories, :subcategories, :articles

end

app/models/article.rb
class Article < ActiveRecord::Base
	belongs_to :subcategory

	validates :name, length: { minimum: 5, maximum: 50 }
	validates :body, length: { minimum: 50,  maximum: 2000 }
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :subcategories

	validates :name, length: { minimum: 5, maximum: 20 }
end

app/models/subcategory.rb
class Subcategory < ActiveRecord::Base
	belongs_to :category
	has_many :articles

	validates :name, length: { minimum: 5, maximum: 20 }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	before_action :authenticate_user!
	add_breadcrumb "Domov", :categories_path

  def index
	  @subcategory = Subcategory.find(params[:id])
	  @articles = @subcategory.articles.all
	  @category = Category.find(@subcategory.category_id) #to je za breadchrumps
	  add_breadcrumb @category.name, controller: 'subcategories', action: 'index', id: @category.id
	  add_breadcrumb @subcategory.name, action: 'index', id: @subcategory.id
  end

  def new
	  @subcategory = Subcategory.find(params[:id])
	  @article = @subcategory.articles.build
	  @category = Category.find(@subcategory.category_id) #to je za breadchrumps
	  add_breadcrumb @category.name, controller: 'subcategories', action: 'index', id: @category.id
	  add_breadcrumb @subcategory.name, action: 'index', id: @subcategory.id
  end

  def create
	  @subcategory = Subcategory.find(params[:id])
	  @article = @subcategory.articles.build(article_params)
	  @category = Category.find(@subcategory.category_id) #to je za breadchrumps
	  add_breadcrumb @category.name, controller: 'categories', action: 'index', id: @category.id
	  add_breadcrumb @subcategory.name, action: 'index', id: @subcategory.id

	  if @article.save
		  redirect_to action: :index, id: @article.subcategory_id
			flash[:notice] = "Uspešno ste dodali nov članek z naslovom #{@article.name}" 
		  else
			  render :new
		  end

  end


  def edit
	  @article = Article.find(params[:id])
	  @subcategory = Subcategory.find(@article.subcategory_id)
	  @category = Category.find(@subcategory.category_id) #to je za breadchrumps
	  add_breadcrumb @category.name, controller: 'subcategories', action: 'index', id: @category.id
	  add_breadcrumb @subcategory.name, action: 'index', id: @subcategory.id
	  add_breadcrumb @article.name, action: 'edit', id: @article.id
  end

  def update
	  @article = Article.find(params[:id])

		if @article.update(article_params)
			redirect_to action: :index, id: @article.subcategory_id 
			flash[:notice] = "Uspešno ste spremenili članek v #{@article.name}" 
			else
				render 'edit'
		end
  end

  def destroy
		@article = Article.find(params[:id])
		@article.destroy
		redirect_to action: :index, id: @article.subcategory_id
			flash[:notice] = "Uspešno ste izbrisali članek z naslovom #{@article.name}" 

  end
	private
	def article_params
		params.require(:article).permit(:name, :body) 

	end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	before_action :authenticate_user!

	add_breadcrumb "Domov", :categories_path

	def index
		@categories = Category.all
	end

	def new
		@category = Category.new
	end

	def create
		@category = Category.new(category_params)

		if @category.save
			redirect_to categories_path
			flash[:notice] = "Uspešno ste ustvarili novo kategorijo #{@category.name}" 
		else
			render 'new'
		end
	end

	def edit
		@category = Category.find(params[:id])
	end

	def update
		@category = Category.find(params[:id])
		if @category.update(category_params)
			redirect_to categories_path
			flash[:notice] = "Uspešno ste spremenili  kategorijo v #{@category.name}" 
			else
				render 'edit'
			end
	end
	 def destroy
		@category = Category.find(params[:id])
		@category.destroy
		redirect_to categories_path
		flash[:notice] = "Uspešno ste izbrisali  kategorijo #{@category.name}" 
	 end

	private
	def category_params
		params.require(:category).permit(:name) 

	end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController

	layout 'news'

	add_breadcrumb "Domov", :root_path

	def index
		@categories = Category.all
	end

	def show

		@categories = Category.all

		@subcategories = Subcategory.find(params[:id])
		@articles = @subcategories.articles

		add_breadcrumb @subcategories.name, news_path

	end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
	private
	    def after_sign_up_path_for(resource)
			    '/categories'
		end
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
	private
	    def after_sign_in_path_for(resource)
			    '/categories'
		end
end

app/controllers/texts_controller.rb
class TextsController < ApplicationController
	layout 'news'

	add_breadcrumb "Domov", :root_path

	def show
		@categories = Category.all
		@article = Article.find(params[:id])
		@subcategorie = Subcategory.find(@article.subcategory_id)

		add_breadcrumb @subcategorie.name, controller: :news, action: :show, id: @subcategorie.id
		add_breadcrumb @article.name, controller: :texts, action: :show, id: @article.id

	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/subcategories_helper.rb
module SubcategoriesHelper
end

app/helpers/texts_helper.rb
module TextsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_devise_navbar.html.erb
<div class="row">
	<nav class="navbar navbar-default" role="navigation">
	<div class="container-fluid">
		<!-- Brand and toggle get grouped for better mobile display -->
		<div class="navbar-header">
		<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
			<span class="sr-only">Toggle navigation</span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
		</button>
		<%= link_to 'Spletna stran', root_path, class: 'navbar-brand' %>
		</div>
	</div><!-- /.container-fluid -->
	</nav>
</div>

app/views/layouts/_navbar.html.erb
<div class="row">
	<nav class="navbar navbar-default" role="navigation">
	<div class="container-fluid">
		<!-- Brand and toggle get grouped for better mobile display -->
		<div class="navbar-header">
		<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
			<span class="sr-only">Toggle navigation</span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
		</button>
		<%= link_to 'Spletna stran', root_path, class: 'navbar-brand' %>
		</div>

		<!-- Collect the nav links, forms, and other content for toggling -->
		<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
		<ul class="nav navbar-nav">
			<% for category in @categories %>
				<li class="dropdown <%= params[:id] %> ">
				<a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= category.name %> <b class="caret"></b></a>
			<ul class="dropdown-menu">
				<% subcategories = category.subcategories.all %>

				<% if subcategories.blank? %>
					<li><a>Ups, ni kategorije!</a></li>
				<% end %>

				<% for subcategory in subcategories %>
					<li>
						<%= link_to subcategory.name, news_path(subcategory) %>
					</li>
				<% end %>
			</ul>
			</li>
			<% end %>
		</ul>
		<ul class="nav navbar-nav navbar-right">
			<% if user_signed_in? %>
				  <li>
				  <button><%= link_to('CMS', categories_path, class: 'btn btn-danger cms-button') %></button>
				  </li>
				<li><a><%= current_user.email %></a></li>
				  <li>
				    <%= link_to('Odjavi se', destroy_user_session_path, :method => :delete) %>
				  </li>
				  <% else %>
					    <li>
						  <%= link_to('Prijavi se', new_user_session_path)  %>
					    </li>
			<% end %> 
		</ul>
		</div><!-- /.navbar-collapse -->
	</div><!-- /.container-fluid -->
	</nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CmsByToni</title>
  <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
  <link href='http://fonts.googleapis.com/css?family=Open+Sans&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Montez|Revalia' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

			<% flash.each do |name, msg| %>
				<% if msg.is_a?(String) %>
				<div class="cms-alert alert alert-<%= name.to_s == 'notice' ? "success" : "danger" %>">
					<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
					<%= content_tag :div, msg, :id => "flash_#{name}" %>
				</div>
				<% end %>
			<% end %>

	<div class="container">
		<div class="row">
			<div class="border-css col-lg-offset-3 col-lg-6">
				<%= link_to news_index_path, title: 'Podji na spletno stran', class: 'no-hover' do %>
					<div class="cms-headline text-center">
						<h1 class="cms">CMS</h1>
						<h5 class=" by-toni">by Toni</h5>
					</div>
				<% end %>
			
					<% if defined?(@home_page) %>
					<% else %>
							<%= render_breadcrumbs %>
					<% end %>

				    <%= link_to('Odjavi se', destroy_user_session_path, :method => :delete, class: "pull-right") %>
					

				<%= yield %>
			</div>
		</div>
	</div>
	<script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
</body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>CmsByToni</title>
		<link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
		<link href='http://fonts.googleapis.com/css?family=Open+Sans&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
		<%= javascript_include_tag "application" %>
		<%= stylesheet_link_tag    "application", media: "all" %>
		<%= csrf_meta_tags %>
	</head>
	<body>
		<div class="container">
			<%= render 'layouts/devise_navbar' %>

			<% flash.each do |name, msg| %>
				<% if msg.is_a?(String) %>
				<div class="alert alert-<%= name.to_s == 'notice' ? "success" : "danger" %>">
					<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
					<%= content_tag :div, msg, :id => "flash_#{name}" %>
				</div>
				<% end %>
			<% end %>

			<%= yield %>
		</div>
		<script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
	</body>
</html>

app/views/layouts/news.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>CmsByToni</title>
		<link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
		<link href='http://fonts.googleapis.com/css?family=Open+Sans&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
		<%= javascript_include_tag "application" %>
		<%= stylesheet_link_tag    "application", media: "all" %>
		<%= csrf_meta_tags %>
	</head>
	<body>
		<div class="container">
			<%= render 'layouts/navbar' %>
			<% if defined?(@home_page) %>
			<% else %>
				<ol class="breadcrumb">
					<%= render_breadcrumbs :tag => :li, :separator => "" %>
				</ol>
			<% end %>

			<% flash.each do |name, msg| %>
				<% if msg.is_a?(String) %>
				<div class="alert alert-<%= name.to_s == 'notice' ? "success" : "danger" %>">
					<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
					<%= content_tag :div, msg, :id => "flash_#{name}" %>
				</div>
				<% end %>
			<% end %>

			<%= yield %>

		</div>
		<script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
	</body>
</html>